steps:
  - name: 'gcr.io/cloud-builders/bash'
    args: ['chmod', '+x', './mvnw']

  - name: 'gcr.io/cloud-builders/bash'
    args: ['./mvnw', 'clean', 'package']
    dir: '.'
    env:
      - 'GOOGLE_RUNTIME_VERSION=17'


  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: '.'
    env:
      - 'GOOGLE_RUNTIME_VERSION=17'


timeout: 900s

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
