steps:
  - name: 'gcr.io/cloud-builders/bash'
    args: ['apt-get', 'update', '-y']

  - name: 'gcr.io/cloud-builders/bash'
    args: ['apt-get', 'install', '-y', 'openjdk-17-jdk']

  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: '.'
    env:
      - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: '.'

options:
  env:
    - 'GOOGLE_BUILDABLE=target'
