steps:
  - name: 'gcr.io/cloud-builders/bash'
    args: ['chmod', '+x', './mvnw']
    
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: '.'


  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: '.'
options:
  env:
    - 'GOOGLE_RUNTIME_VERSION=17'
