steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

options:
  logging: CLOUD_LOGGING_ONLY
